# Generated by Django 5.1.7 on 2025-05-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0006_userprofile_review_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
