# Generated by Django 5.1.7 on 2025-05-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0009_deliveryaddress_userprofile_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='member_since',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
