# Generated by Django 5.1.7 on 2025-05-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0010_userprofile_member_since'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='member_since',
        ),
    ]
