# Generated by Django 5.1.7 on 2025-08-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomm", "0013_order_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="khalti_payment_id",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Packed", "Packed"),
                    ("Getting ready for delivery", "Getting ready for delivery"),
                    ("Delivered", "Delivered"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
