# Generated by Django 5.1.7 on 2025-08-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomm", "0015_passwordresetotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
