# Generated by Django 5.1.7 on 2025-08-15 16:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomm", "0016_order_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="transaction_uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
